// Generated by scripts/export-layers.mjs from KiCad's layer colours.
export const layerColours = {
  "B_Cu-traces": "#4D7FC4",
  "In2_Cu-traces": "#CE7D2C",
  "In1_Cu-traces": "#7FC87F",
  "F_Cu-traces": "#C83434",
  "B_Cu-pour": "#4D7FC4",
  "In2_Cu-pour": "#CE7D2C",
  "In1_Cu-pour": "#7FC87F",
  "F_Cu-pour": "#C83434",
  F_Silkscreen: "#F2EDA1",
};
